# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_abc_to_mti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseold',
            name='speakers',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['start'], 'verbose_name': 'mini-curso', 'verbose_name_plural': 'mini-cursos'},
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['start'], 'verbose_name': 'palestra', 'verbose_name_plural': 'palestras'},
        ),
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
